Модуль 9 Задание 1
htmlacademy-php/448331-readme-12 pull request #16
Opened 2022-05-28 20:16 UTC by andrey-white

2022-06-06 09:32 UTC, pyatnitsev requested changes
Минорные изменения, в целом - неплохо.

2022-06-06 09:32 UTC, pyatnitsev commented on composer.json
> +    "minimum-stability": "dev",
лучше - stable

2022-06-06 09:32 UTC, pyatnitsev commented on functions.php
> +    if ($user_exists[0]) {
не очень красиво, лучше использовать точные сравнения - ```return isset($user_exists[0]) && $user_exists[0] > 0```;

2022-06-06 09:32 UTC, pyatnitsev commented on mailer.php
> +$mail_dsn = 'smtp://phptest@ni-bel.ru:j8kmz201A@mail.nic.ru';
в рамках учебного занятия - ок, 
но вообще хранить пароли внутри приложения не ок, лучше использовать переменные окружения

2022-06-06 09:32 UTC, pyatnitsev commented on messages.php
> +			$return_page = "Location: messages.php?chat_mate_id=".$_POST['recipient_id'];
вот такое обращение может быть потенциально не безопасным, лучше приводить его явно в int: ```(int) $_POST['recipient_id']```

2022-06-29 14:46 UTC, pyatnitsev approved these changes
Ок, принято, разве что я написал другую версию пакета - нужно использовать стабильные

2022-06-29 14:46 UTC, pyatnitsev commented on composer.json
> +        "symfony/mailer": "5.4.x-dev"
"symfony/mailer": "^5.4"

2022-06-29 14:46 UTC, pyatnitsev commented on mailer.php
> +$mail_dsn = $_ENV['SYMFONY_MAILER_DSN'];
а работает?

2022-06-29 14:46 UTC, merged

2022-07-02 19:48 UTC, andrey-white commented on mailer.php
> +$mail_dsn = $_ENV['SYMFONY_MAILER_DSN'];
Заработало, но не сразу, пришлось лезть в php.ini, до этого не было доступа к массиву с переменными окружения.